### ISSUE TITLE
(S) Obscure text in password fields. 

### ISSUE THREAD

**Issue by ivwang46** [Hack4Impact-Princeton/alp-portal#48]
Hide text in password fields on login and signup pages!! 

Look at the examples on [this page](https://mui.com/material-ui/react-text-field/) under the heading "Input Adornments"

Add an eye icon from MUI Icons that, when clicked, toggles a state that controls visibility.

**Comment by crimmzx** [comment]
thanks.
Best,William Zhang
Princeton ***@***.***  





On Wed, Jun 7, 2023 at 6:52 PM Ivy Wang ***@***.***>  wrote:


Assigned #48  to @crimmzx.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were assigned.Message ID: 
***@***.***>



Best,

William Zhang




Princeton ***@***.***
